name: Deploy wine-app-frontend

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}     
      - name: Build Docker Image
        run: docker build -t tranvix0910/wine_app_frontend  .


      - name: Publish Image to docker hub
        run: docker push tranvix0910/wine_app_frontend:latest
 
  deploy:
    needs: build
    runs-on: self-hosted 
    steps:
      - name: Pull image from docker hub
        run: docker pull tranvix0910/wine_app_frontend:latest
      - name: Delete old container
        run: docker rm -f wine_app_frontend-container
      - name: Run Docker Container
        run: docker run -d -p 3000:80 --name wine_app_frontend-container tranvix0910/wine_app_frontend